apiVersion: v1
kind: Service
metadata:
  name: orders-api
  labels:
    tier: backend
    app: delivery
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 8585
      # Optional field,
      nodePort: 30080
  selector:
    api: orders
